version: '3.8'  # Vous pouvez le retirer si cette ligne est obsolète pour vous

services:
  fastapi:
    build:
      context: ./app  # Chemin vers votre Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env  # Assurez-vous que le chemin est correct

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

