version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  
  nginx:
    build:
      context: ./nginx  # Assurez-vous que ce chemin est correct
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - fastapi

